# Generated by Django 4.1.9 on 2023-05-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
