# Generated by Django 4.1.9 on 2023-05-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_alter_profile_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
