# Generated by Django 4.1.9 on 2023-05-31 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_profileupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileUpdate',
        ),
    ]
