# Generated by Django 4.1.9 on 2023-05-31 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_profileupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileUpdate',
        ),
    ]
