# Generated by Django 4.1.9 on 2023-06-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_support'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Admin_Profile',
        ),
    ]
