# Generated by Django 4.1.9 on 2023-07-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_rename_profile_admin_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_No', models.CharField(max_length=42)),
                ('Patient_Name', models.CharField(max_length=42)),
                ('Phone_Number', models.CharField(max_length=42)),
                ('Email', models.EmailField(max_length=254)),
                ('Assigned_Therapist', models.CharField(max_length=42)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Address', models.CharField(max_length=42)),
                ('Total_Amount', models.CharField(max_length=42)),
                ('Payment_Method', models.CharField(max_length=42)),
                ('Payment_Status', models.CharField(max_length=42)),
            ],
        ),
    ]
