# Generated by Django 4.1.9 on 2023-07-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_admin_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_Invoice',
        ),
    ]
