# Generated by Django 4.1.9 on 2023-07-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0018_admin_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_invoice',
            name='Date',
            field=models.CharField(max_length=42),
        ),
    ]
