# Generated by Django 4.1.9 on 2023-06-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_appointments',
            fields=[
                ('Patient_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Appointment_id', models.CharField(editable=False, max_length=4, unique=True)),
                ('Name', models.CharField(max_length=42)),
                ('Email', models.EmailField(max_length=254)),
                ('Therapist_Name', models.CharField(max_length=42)),
                ('Date', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('First_Name', models.CharField(max_length=42)),
                ('Last_Name', models.CharField(max_length=42)),
                ('Username', models.CharField(max_length=42)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.IntegerField(default=0)),
                ('Password', models.CharField(max_length=42)),
                ('Confirm_Password', models.CharField(max_length=42)),
                ('otp', models.CharField(blank=True, editable=False, max_length=6, null=True)),
                ('token', models.CharField(blank=True, max_length=10, null=True)),
                ('uid', models.CharField(editable=False, max_length=4, unique=True)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=42)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.CharField(max_length=42)),
            ],
        ),
    ]
