# Generated by Django 4.1.9 on 2023-06-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_appointments',
        ),
    ]
