# Generated by Django 4.1.9 on 2023-06-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_remove_book_appointments_patient_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_appointments',
        ),
    ]
