# Generated by Django 4.1.9 on 2023-06-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_delete_book_appointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_appointments',
            fields=[
                ('Appointment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=42)),
                ('Email', models.EmailField(max_length=254)),
                ('Therapist_Name', models.CharField(max_length=42)),
                ('Date', models.CharField(max_length=42)),
            ],
        ),
    ]
