# Generated by Django 4.1.9 on 2023-06-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_book_appointments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_appointments',
        ),
    ]
