# Generated by Django 4.1.9 on 2023-06-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_delete_book_appointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_appointments',
            fields=[
                ('Appointment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=42)),
                ('Date', models.CharField(max_length=42)),
                ('Problem', models.CharField(max_length=42)),
                ('Supervisor_Name', models.CharField(max_length=42)),
                ('Therapist_Name', models.CharField(max_length=42)),
            ],
        ),
    ]
