# Generated by Django 4.1.9 on 2023-07-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_book_appointments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_appointments',
        ),
    ]
