# Generated by Django 4.1.9 on 2023-06-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
