# Generated by Django 4.1.9 on 2023-06-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Superadmin_Profile',
        ),
    ]
