# Generated by Django 4.1.9 on 2023-06-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=42)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.CharField(max_length=42)),
            ],
        ),
    ]
