# Generated by Django 4.1.9 on 2023-06-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0004_support'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Supervisor_Profile',
        ),
    ]
