# Generated by Django 4.1.9 on 2023-07-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0007_supervisor_profile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor_profile',
            name='Specialisation',
            field=models.CharField(default='', max_length=42),
        ),
    ]
